### ISSUE TITLE
Error during package installation on Ubuntu

### ISSUE THREAD

**Issue by Davide-sd** [scivision/geomag-indices#1]
OS: Ubuntu 18.04
Python 3.6

I tried to install this package with the command: `sudo python3 -m pip install geomagindices` but I got an error during installation. Here is the traceback:

```
Collecting geomagindices
  Downloading https://files.pythonhosted.org/packages/41/50/779336fb12dda885de66b742ac0d9d4a4d6155c101c4a7e5d6435b149fe0/geomagindices-1.1.0.tar.gz (70kB)
    100% |████████████████████████████████| 71kB 375kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-yabpiw8w/geomagindices/setup.py", line 3, in <module>
        setup()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 121, in _install_setup_requires
        dist.parse_config_files(ignore_option_errors=True)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/dist.py", line 485, in parse_config_files
        ignore_option_errors=ignore_option_errors)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/config.py", line 110, in parse_configuration
        options.parse()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/config.py", line 380, in parse
        self.section_prefix, section_name))
    distutils.errors.DistutilsOptionError: Unsupported distribution option section: [options.data_files]
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-yabpiw8w/geomagindices/
```

**Comment by scivision** [comment]
setuptools >= 40.6 is required:

`pip install --upgrade setuptools` 

Thanks!

**Comment by Davide-sd** [comment]
Solved, thank you!
